# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'movieApp' do

  # Pods for movieApp
  pod 'Moya', '~> 13.0'
  pod 'RealmSwift'

  
target 'movieAppTests' do
  # Pods for movieAppTests
  pod 'Quick'
  pod 'Nimble'
end


end
